# Use postgres/example user/password credentials
version: '3.1'

services:
  distributed-lock:
    image: distributed-lock:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=default"
    ports:
    - 8080:8080

#  db:
#    image: postgres
#    environment:
#      PGDATA: /var/lib/postgresql/data/pgdata
#      POSTGRES_HOST_AUTH_METHOD: trust
#    volumes:
#    - D:/postgres:/var/lib/postgresql/data postgres

#  db:
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    environment:
#      MYSQL_ROOT_PASSWORD: 12345678
volumes:
  mariadb_data:
    driver: local