apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributed-lock
  labels:
    app: backend
spec:
  replicas: 4
#  strategy:
#    type: RollingUpdate
#    rollingUpdate:
#      maxSurge: 1
#      maxUnavailable: 1
  selector:
    matchLabels:
      app: backend
      track: stable
  template:
    metadata:
      labels:
        app: backend
        track: stable
    spec:
      containers:
        - name: distributed-lock
          image: distributed-lock:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
